version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: promresource-postgres-service
    restart: always
    volumes:
      - ./postgres-service/data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  api:
    container_name: promresource-api-service
    image: strapi/strapi:alpine
    restart: always
    volumes:
      - ./api-service/app:/srv/app
    depends_on:
      - postgres
    ports:
      - ${API_PORT}:1337
    environment:
      # NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_CLIENT: ${API_DATABASE_CLIENT}
      DATABASE_NAME: ${POSTGRES_DB}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
    # command: 'strapi start'

  web:
    container_name: promresource-web-service
    restart: always
    build:
      context: ./web-service
    volumes:
      - ./web-service:/app
      - /app/node_modules
      - /app/.sessions
    depends_on:
      - api
    ports:
      - ${WEB_SERVICE_PORT}:3000
      - 24678:24678
    environment:
      JWT_SECRET: ${JWT_SECRET}
      APP_HOST: ${APP_HOST}
      API_HOST: api
      API_PORT: ${API_PORT}
      IO_HOST: web
      IO_PORT: 3000
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      FCM_API_KEY: ${FCM_API_KEY}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}

  reverse-proxy:
    image: asknotbad/nginx-reverse-proxy:alpine
    container_name: promresource-reverse-proxy-service
    restart: always
    volumes:
      - ./reverse-proxy-service/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./reverse-proxy-service/nginx/conf.d:/etc/nginx/conf.d
      - ./reverse-proxy-service/nginx/sites-available:/etc/nginx/sites-available
      - ./reverse-proxy-service/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./reverse-proxy-service/log:/var/log/nginx
    depends_on:
      - web
    ports:
      - 80:80
    environment:
      APP_HOST: ${APP_HOST}
      WEB_SERVICE_HOST: web
      WEB_SERVICE_PORT: ${WEB_SERVICE_PORT}
      API_HOST: api
      API_PORT: ${API_PORT}
