name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 10
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      FCM_API_KEY: ${{ secrets.FCM_API_KEY }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      WEB_SERVICE_PORT: ${{ secrets.WEB_SERVICE_PORT }}
      API_HOST: ${{ secrets.API_HOST }}
      API_PORT: ${{ secrets.API_PORT }}
      API_DATABASE_CLIENT: ${{ secrets.API_DATABASE_CLIENT }}
      APP_HOST: ${{ secrets.APP_HOST }}
      TRAEFIK_HOST: ${{ secrets.TRAEFIK_HOST }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up --build -d

      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose.yml -f docker-compose.prod.yml down

  deploy:
    needs: [test]
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd promresource
            git fetch origin
            git reset --hard origin/main
            git pull
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up --build -d
            docker system prune --volumes -f
            exit
